region: "sa-east-1"
public_dns_zone: "ck.osecloud.com"
public_subdomain_prefix: "apps"
aws_key_pair: "ck_saop"
#ami_id: "ami-0e88cb62"
ami_id: "ami-5bb1fd37"

install_metrics: true
install_prometheus: true
install_logging: true

install_gluster: true
gluster_ami_size: t2.large
gluster_volume_size: 100

users:
  - {name: admin, password: Welcome1, admin: true}
create_generic_user: true
generic_user_prefix: developer
generic_user_count: 5
generic_user_password: Welcome1

bastion_ami_size: "t2.small"
master_ami_size: "t2.large"
node_ami_size: "t2.large"

master_root_volume_size: 50
node_root_volume_size: 30
docker_volume_size: 50

app_nodes: 3
deployment_type: "openshift-enterprise"
ocp_version: "3.7"

namespace: "openshift"
dns_zone: "ose.local"
vpc_cidr: "10.0.0.0/16"
subnet_cidr: "10.0.1.0/24"
amazon_user: "ec2-user"
htpasswd_path: "/etc/origin/master/htpasswd"
